# Node.js
jobs:
- job: DeploymentJob
  displayName: 'Deployment Job'
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: AzureRmWebAppDeployment@4
    displayName: 'Azure RM Web App Deployment'
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure for Students(afe8d0a7-5b2e-4452-bbeb-5b176d9c8150)'
      appType: 'webApp'
      WebAppName: 'react-saqlain-app'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

- job: BuildJob
  displayName: 'Build Job'
  pool:
    vmImage: ubuntu-latest
  
  steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '10.x'
  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'
